inherit_from: .rubocop_todo.yml
AllCops:
  Exclude:
    - bin/*
    - db/schema.rb
    - tmp/**/*
    - app/views/**/*
Lint/AmbiguousRegexpLiteral:
  Enabled: true
Lint/AssignmentInCondition:
  Enabled: true
